/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import pq1.impProductos;
import pq3.Producto;

/**
 *
 * @author santiagob20
 */
public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    static int precio;
    static int impuesto;
    static int total;
    Producto p = new Producto();
    
    public grafica() {
        initComponents();
        this.setSize(new Dimension(807, 679));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtValorP = new javax.swing.JTextField();
        valorP = new javax.swing.JLabel();
        txtImp = new javax.swing.JTextField();
        categoria = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JToggleButton();
        Nombre4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Nombre.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setText("Nombre del producto");
        getContentPane().add(Nombre);
        Nombre.setBounds(240, 150, 160, 20);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(410, 150, 190, 24);

        txtValorP.setText("0");
        txtValorP.setToolTipText("");
        txtValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPActionPerformed(evt);
            }
        });
        txtValorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorPKeyTyped(evt);
            }
        });
        getContentPane().add(txtValorP);
        txtValorP.setBounds(410, 190, 190, 24);

        valorP.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valorP.setForeground(new java.awt.Color(51, 51, 51));
        valorP.setText("Valor para calcular impuesto");
        getContentPane().add(valorP);
        valorP.setBounds(190, 190, 210, 20);

        txtImp.setEditable(false);
        txtImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpActionPerformed(evt);
            }
        });
        getContentPane().add(txtImp);
        txtImp.setBounds(410, 270, 190, 24);

        categoria.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        categoria.setForeground(new java.awt.Color(51, 51, 51));
        categoria.setText("Categoria");
        getContentPane().add(categoria);
        categoria.setBounds(320, 230, 70, 20);

        Nombre3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(51, 51, 51));
        Nombre3.setText("Impuesto calculado");
        getContentPane().add(Nombre3);
        Nombre3.setBounds(260, 270, 140, 20);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "19% Tecnología", "20% Finca raiz", "15% Canasta familiar", "9% Otro" }));
        cmbCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategoria);
        cmbCategoria.setBounds(410, 230, 190, 26);

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(410, 310, 190, 24);

        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(310, 430, 190, 40);

        Nombre4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(51, 51, 51));
        Nombre4.setText("Total");
        getContentPane().add(Nombre4);
        Nombre4.setBounds(360, 310, 50, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/impuesto.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 807, 679);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarImp(String seleccion){
        
            switch(seleccion){
                case "19% Tecnología":
                    precio = Integer.parseInt(txtValorP.getText());
                    impuesto = (int) (precio*0.19);
                    total = precio+impuesto;
                    txtImp.setText(String.valueOf(impuesto));
                    txtTotal.setText(String.valueOf(total));
                    break;

                case "20% Finca raiz":
                    precio = Integer.parseInt(txtValorP.getText());
                    impuesto = (int) (precio*0.20);
                    total = precio+impuesto;
                    txtImp.setText(String.valueOf(impuesto));
                    txtTotal.setText(String.valueOf(total));
                    break;

                case "15% Canasta familiar":
                    precio = Integer.parseInt(txtValorP.getText());
                    impuesto = (int) (precio*0.15);
                    total = precio+impuesto;
                    txtImp.setText(String.valueOf(impuesto));
                    txtTotal.setText(String.valueOf(total));
                    break;

                case "9% Otro":
                    precio = Integer.parseInt(txtValorP.getText());
                    impuesto = (int) (precio*0.09);
                    total = precio+impuesto;
                    txtImp.setText(String.valueOf(impuesto));
                    txtTotal.setText(String.valueOf(total));
                    break;

                case "Seleccione...":
                    txtImp.setText("");
                    txtTotal.setText("");
            }
        }
    
    private void guardarProducto(){
        
        p.setNombre(txtNombre.getText());
        p.setValorP(Integer.parseInt(txtValorP.getText()));
        p.setCategoria(cmbCategoria.getSelectedItem().toString());
        p.setValorImp(Integer.parseInt(txtImp.getText()));
        p.setTotal(Integer.parseInt(txtTotal.getText()));
    }
    private void borrarCampos(){
        txtNombre.setText("");
        txtValorP.setText("");
        txtImp.setText("");
        txtTotal.setText("");
        cmbCategoria.setSelectedIndex(0);
    }
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPActionPerformed

    private void txtImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpActionPerformed

    private void txtValorPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)&& c!=KeyEvent.VK_BACK_SPACE){ 
              getToolkit().beep(); 
              evt.consume(); 
              JOptionPane.showMessageDialog(null,"Error, Solo puede ingresar numeros",null,JOptionPane.ERROR_MESSAGE);
          }    
    }//GEN-LAST:event_txtValorPKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        impProductos imp = new impProductos();
        
        if (txtNombre.getText().isEmpty()||txtValorP.getText().isEmpty()||txtImp.getText().isEmpty()||txtTotal.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos", "¡Error!", JOptionPane.ERROR_MESSAGE);    
        }
        guardarProducto();
        imp.insertar(p);
        borrarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        String seleccion;
        seleccion=cmbCategoria.getSelectedItem().toString();
        seleccionarImp(seleccion);
    }//GEN-LAST:event_cmbCategoriaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JLabel categoria;
    public javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField txtImp;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorP;
    private javax.swing.JLabel valorP;
    // End of variables declaration//GEN-END:variables
}
